#This message is used to send command to tetra
#Parameter read command

---
int32 p0_uart1_baudrate
int32 p1_uart2_baudrate
int32 p2_mode_select
int32 p3_outport
int32 p4_nc
int32 p5_nc
int32 p6_nc
int32 p7_conveyor_dir
int32 p8_conveyor_timeout
int32 p9_fix_loading_start_delay
int32 p10_fix_loading_end_delay
int32 p11_fix_unloading_start_delay
int32 p12_fix_unloading_motor_delay
int32 p13_fix_unloading_end_delay
int32 p14_loading_start_delay
int32 p15_loading_end_delay
int32 p16_unloading_start_delay
int32 p17_unloading_end_delay
int32 p18_express_quantity
int32 p19_termianl_loading_base
int32 p20_termianl_unloading_base

bool command_result

