#This message is used to send command to tetra
#Goto Location command

string location
---
float64 pose_x
float64 pose_y
float64 pose_z
float64 pose_qx
float64 pose_qy
float64 pose_qz
float64 pose_qw
bool command_result
