#This message is used to send command to tetra
#LED Toggle Control command

int32 de_index
int32 light_accel
int32 led_high_brightness
int32 light_decel
int32 led_low_brightness
---
bool command_result
