#This message is used to send command to tetra
#Set GPIO Output On/Off command

int8 output0
int8 output1
int8 output2
int8 output3
int8 output4
int8 output5
int8 output6
int8 output7

---
bool command_result

