#This message is used to send command to tetra
#PowerSensor BD system data read command

---
int32 d0_battery_voltage
int32 d1_system_current
int32 d2_charge_current
int32 d3_charge_signal
int32 d4_inport_status
int32 d5_outport_status
int32 d6_power_status
int32 d7_charge_terminal_status
int32 d8_temperature0
int32 d9_temperature1
int32 d10_mobd_inport_status
int32 d11_mobd_outport_status

bool command_result

