#This message is used to send command to tetra
#Parameter read command

---
int32 p0_uart1_baudrate
int32 p1_uart2_baudrate
int32 p2_sonar_select
int32 p3_sonar_distance_offset
int32 p4_sonar_quantity
int32 p5_sonar_max_distance
int32 p6_nc
int32 p7_sonar_none_detect_mode
int32 p8_battery_charging_offest
int32 p9_battery_charging_gain
int32 p10_status_led_min
int32 p11_status_led_max
int32 p12_battery_led_min
int32 p13_battery_led_max
int32 p14_led_ch1_offest
int32 p15_led_ch2_offest
int32 p16_led_ch3_offest
int32 p17_led_ch4_offest
int32 p18_led_ch5_offest
int32 p19_led_ch6_offest
int32 p20_led_ch7_offest
int32 p21_led_ch8_offest
int32 p22_power_enable
int32 p23_outport
int32 p24_battery_recharge_voltage
int32 p25_battery_recharge_offset
int32 p26_battery_min
int32 p27_battery_max
int32 p28_battery_sampling_time
int32 p29_conveyor_mode
int32 p30_conveyor_terminal_base
int32 p31_conveyor_terminal_offset
bool command_result

