#This message is used to send command to tetra
#PowerSensor BD Sonar data read command

---
int32 d0_sonar0
int32 d1_sonar1
int32 d2_sonar2
int32 d3_sonar3
int32 d4_sonar4
int32 d5_sonar5

bool command_result

