scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: scan_blob_filter
      type: laser_filters/ScanBlobFilter
      params:
        max_radius: 0.4 # maximum radius to be considered as blob object
        min_points: 3 # min scan points to be considered as blob object
