image_width: 640
image_height: 480
camera_name: rear_camera
camera_matrix:
  rows: 3
  cols: 3
  data: [846.72684,   0.     , 316.07951,
           0.     , 848.33153, 272.58258,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.168309, -0.295912, 0.006336, -0.010750, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [865.55194,   0.     , 311.49615,   0.     ,
           0.     , 870.62292, 273.67153,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
